services:
  postgres_test:
    image: postgres:latest
    restart: always
    env_file:
      - /.env.test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    

volumes:
  postgres_test_data:
